[versions]
# libraries
activityCompose = "1.11.0"
androidXTest = "1.7.0"
androidXTestRunner = "1.7.0"
androidXTestMonitor = "1.8.0"
appcompat = "1.7.1"
bcprovJdk16 = "1.46"
biometricKtx = "1.2.0-alpha05"
cameraCore = "1.5.1"
coreKtx = "1.17.0"
documentfile = "1.1.0"
featureDeliveryKtx = "2.1.0"
firebaseBom = "34.5.0"
guava = "33.5.0-android"
junit = "4.13.2"
junit5 = "5.11.3"
junit6 = "6.0.0"
junitVersion = "1.3.0"
junitVersionKtx = "1.3.0"
kotlinStdlib = "2.2.21"
kotlinxCoroutinesCore = "1.10.2"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJson = "1.9.0"
kxml2 = "2.3.0"
lintTestsVersion = "31.13.0"
material = "1.13.0"
material3Android = "1.4.0"
materialIconsExtendedAndroid = "1.7.8"
mockk = "1.14.6"
napier = "2.7.1"
okio = "3.16.2"
preferenceKtx = "1.2.1"
runtimeLivedataVersion = "1.9.4"
uiTestJunit4Android = "1.9.4"
uiTooling = "1.9.4"
uiToolingPreviewAndroid = "1.9.4"
uiautomator = "2.3.0"
volley = "1.2.1"
#plugins
agp = "8.13.0"
# see also dependency resolution in settings.gradle.kts for 2.0.21!
jetbrainsKotlinJvm = "2.2.21"
kotlin = "2.2.21"
uiTestAndroid = "1.9.4"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-biometric-ktx = { group = "androidx.biometric", name = "biometric-ktx", version.ref = "biometricKtx" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraCore" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraCore" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraCore" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidXTest" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-material-icons-extended-android = { group = "androidx.compose.material", name = "material-icons-extended-android", version.ref = "materialIconsExtendedAndroid" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-monitor = { module = "androidx.test:monitor", version.ref = "androidXTestMonitor" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedataVersion" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-test-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitVersionKtx" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidXTest" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidXTestRunner" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
androidx-ui-test-android = { group = "androidx.compose.ui", name = "ui-test-android", version.ref = "uiTestAndroid" }
androidx-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "uiTestJunit4Android" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "uiTestJunit4Android" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
androidx-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "featureDeliveryKtx" }
bcprov-jdk16 = { module = "org.bouncycastle:bcprov-jdk16", version.ref = "bcprovJdk16" }
feature-delivery-ktx = { group = "com.google.android.play", name = "feature-delivery-ktx", version.ref = "featureDeliveryKtx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit5_bom = { group = "org.junit", name = "junit-bom", version.ref = "junit5" }
junit5_jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }
# far in the future
junit6_bom = { group = "org.junit", name = "junit-bom", version.ref = "junit6" }
junit6_jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit6" }
junit6_platform = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit6" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kxml2 = { group = "net.sf.kxml", name = "kxml2", version.ref = "kxml2" }
lint-tests-v3000 = { module = "com.android.tools.lint:lint-tests", version.ref = "lintTestsVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
napier = { group = "io.github.aakira", name = "napier", version.ref = "napier" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedataVersion" }
ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "uiTestJunit4Android" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
